### ISSUE TITLE
Pre-hunt checklist

### ISSUE THREAD

**Issue by Torgen** [Torgen/codex-blackboard#24]
- [x] Create burner gmail account
- [x] Subscribe GMail account to puzzle-hunters list
- [x] Subscribe GMail account to loopfinders
- [x] Create filter and label for puzzle-hunters list
- [x] Create filter for from:puzzle@mit.edu to same label
- [x] Register Domain
- [x] Create VM with static IP and extra SSD
- [x] Set scopes on VM
- [x] Set A record for domain to static IP
- [x] Enable PTR record
- [x] Create xfs partition on SSD and add to fstab
- [x] Run install script
- [x] Allow HTTP and HTTPS through firewall
- [x] Set burner gmail account as owner for created drive files
- [x] Set twitter app credentials for scraping
- [x] Disable mail polling on staging server
- [x] Configure polling the puzzle hunters label for the burner gmail account.
- [x] Build 64 core VM for brute forcing
- [x] Install compilers on brute force VM
  - [x] Haskell
  - [x] Golang
- [x] Stop brute force VM. (It will cost $2+ per hour to run, albeit from free trial credit.)
- [x] Send URL/Login/Password to loopfinders and pin that thread to the top
- [x] Scrape useful info from wiki into doc
- [x] Put info doc in loopfinders shared folder
